###################################################### Splunk ######################################################
hostname: 'splunk'
splunk_version: '8.1.2'

# https://www.splunk.com/en_us/download/splunk-enterprise.html
splunk_dl_url: 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version={{ splunk_version }}&product=splunk&filename=splunk-{{ splunk_version }}-545206cc9f70-linux-2.6-amd64.deb&wget=true'

###################################################### Logstash ######################################################
beats_port: 5044
elastic_version: 7.10.0
elastic_repo_version: '7.x'
elastic_gpg_url: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
elastic_repo_url: 'deb https://artifacts.elastic.co/packages/{{ elastic_repo_version }}/apt stable main'