###################################################### Splunk ######################################################
hostname: 'splunk'
splunk_version: '8.0.7'

# https://www.splunk.com/en_us/download/splunk-enterprise.html
SPLUNK_DL_URL: 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version={{ SPLUNK_VERSION }}&product=splunk&filename=splunk-{{ SPLUNK_VERSION }}-cbe73339abca-linux-2.6-amd64.deb&wget=true'