###################################################### Splunk ######################################################
hostname: 'splunk'
splunk_version: '8.1.2'

# https://www.splunk.com/en_us/download/splunk-enterprise.html
splunk_dl_url: 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=8.1.2&product=splunk&filename=splunk-8.1.2-545206cc9f70-linux-2.6-amd64.deb&wget=true'