- hosts: 'splunk'
  become: yes
  become_user: root
  tasks:
    - include_vars: 'group_vars/splunk.yml'
    - import_tasks: 'roles/init.yml'
    - import_tasks: 'roles/splunk/setup_splunk.yml'
    - import_tasks: 'roles/splunk/setup_nginx.yml'
    - import_tasks: 'roles/splunk/setup_splunk_hec.yml'
    - import_tasks: 'roles/logstash/setup_logstash.yml'
    - import_tasks: 'roles/splunk/setup_ufw.yml'