version: "3.9"
services: 
  ###################################################### NGINX ######################################################
  nginx:
    image: nginx:1.19.6-alpine
    configs:
      - source: nginx-conf
        target: /etc/nginx/nginx.conf
      - source: nginx-splunk-conf
        target: /etc/nginx/conf.d/splunk.conf
    secrets:
      - source: nginx-tls-cert
        target: /etc/ssl/certs/nginx.crt
      - source: nginx-tls-key
        target: /etc/ssl/private/nginx.key
    networks: 
      - default
      - splunk-backend 
    ports:
      - 8000:80
      - 8443:443
      - 8089:8089
      - 8088:8088
    depends_on: 
      - splunk
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 150M
        reservations:
          cpus: '0.25'
          memory: 100M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 120s

  ###################################################### Splunk ######################################################
  splunk:
    image: splunk/splunk:8.1.1-debian
    secrets:
      - source: splunk-default-conf
        target: /tmp/defaults/default.yml
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ADD=tcp 1514
    ports: 
      - 9997:9997
    networks: 
      - default
      - splunk-backend
    volumes: 
      - splunk-var:/opt/splunk/var
      - splunk-etc:/opt/splunk/etc
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 500M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 120s

  ###################################################### Logstash ######################################################
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    environment: 
       - xpack.monitoring.enabled=false
    configs:
      #### inputs ####
      - source: logstash-input-conf
        target: /usr/share/logstash/pipeline/logstash.conf
      #### filters ####
      - source: logstash-filter-zeek-conf
        target: /usr/share/logstash/pipeline/10-filter-zeek.conf
      - source: logstash-filter-sysmon-conf
        target: /usr/share/logstash/pipeline/11-filter-sysmon.conf
      - source: logstash-filter-osquery-conf
        target: /usr/share/logstash/pipeline/13-filter-osquery.conf
      #### outputs ####
      - source: logstas-output-splunk-syslog-conf
        target: /usr/share/logstash/pipeline/30-output-splunk-syslog.conf
    secrets:
      - source: nginx-tls-cert
        target: /etc/pki/tls/certs/logstash.crt
        uid: '1000'
        gid: '1000'
        mode: 0644
      - source: nginx-tls-key
        target: /etc/pki/tls/private/logstash.key
        uid: '1000'
        gid: '1000'
        mode: 0400
    networks: 
      - default
      - splunk-backend 
    ports:
      - 5044:5044
    depends_on: 
     - splunk
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 500M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 120s

networks: 
  splunk-backend:

volumes: 
  splunk-var:
  splunk-etc:

configs:
  nginx-conf:
    file: ./conf/docker/nginx/nginx.conf
  nginx-splunk-conf:
    file: ./conf/docker/nginx/splunk.conf
  logstash-input-conf:
    file: ./conf/docker/splunk/02-input-beats.conf
  logstash-filter-zeek-conf:
    file: ./conf/logstash_filters/10-filter-zeek.conf
  logstash-filter-sysmon-conf:
    file: ./conf/logstash_filters/11-filter-sysmon.conf
  logstash-filter-osquery-conf:
    file: ./conf/logstash_filters/13-filter-osquery.conf
  logstas-output-splunk-syslog-conf:
    file: ./conf/docker/splunk/30-output-splunk-syslog.conf

secrets:
  nginx-tls-cert:
    file: ./conf/tls/tls.crt
  nginx-tls-key:
    file: ./conf/tls/tls.key
  splunk-default-conf:
    external: true