ARG ELASTIC_VERSION
FROM docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}

# Instal Logstash plugins
RUN logstash-plugin install logstash-filter-json_encode

# Copy TLS cert and private key
COPY conf/tls/*.crt /etc/pki/tls/certs/logstash.crt
COPY conf/tls/*.key /etc/pki/tls/private/logstash.key

# Set TLS cert and private key perms
USER root
RUN chown logstash /etc/pki/tls/certs/logstash.crt && chown logstash /etc/pki/tls/private/logstash.key
RUN chmod 644 /etc/pki/tls/certs/logstash.crt && chmod 400 /etc/pki/tls/private/logstash.key
USER logstash

# Copy pipeline configs
RUN rm /usr/share/logstash/pipeline/logstash.conf
COPY conf/logstash_filters/ /usr/share/logstash/pipeline
COPY conf/docker/splunk/02-input-beats.conf /usr/share/logstash/pipeline/02-input-beats.conf
COPY conf/docker/splunk/30-output-splunk-syslog.conf /usr/share/logstash/pipeline/30-output-splunk-syslog.conf
