ARG GRAYLOG_VERSION
FROM graylog/graylog:${GRAYLOG_VERSION}
ARG SIEM_USERNAME
ARG SIEM_PASSWORD

# Copy TLS
RUN mkdir /usr/share/graylog/tls
COPY conf/tls/*.crt /usr/share/graylog/tls/graylog.crt
COPY conf/tls/*.key /usr/share/graylog/tls/graylog.key
USER root
RUN chown root:graylog /usr/share/graylog/tls/graylog.key && \
    chmod 640 /usr/share/graylog/tls/graylog.key
USER graylog

# Copy BEATS input script
COPY conf/docker/graylog/generate_beats_input.sh /usr/share/graylog/generate_beats_input.sh
RUN sed -i "s/graylog-test-user/${SIEM_USERNAME}/g" /usr/share/graylog/generate_beats_input.sh
RUN sed -i "s/graylog-test-password/${SIEM_PASSWORD}/g" /usr/share/graylog/generate_beats_input.sh
RUN chmod +x /usr/share/graylog/generate_beats_input.sh