####################################################################
# Setup kafka as the input
####################################################################
- name: Copy Kafka input config
  template:
    src: 'conf/ansible/splunk/03-input-kafka.conf'
    dest: '/etc/logstash/conf.d/03-input-kafka.conf'
    owner: logstash
    group: logstash

- name: Remove BEATs input
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - '/etc/logstash/conf.d/02-input-beats.conf'
    - '/etc/logstash/conf.d/30-output-splunk-hec.conf'

####################################################################
# Create Splunk HEC inputs
####################################################################
- name: Sign into Splunk
  uri:
    url: "https://127.0.0.1:8089/servicesNS/admin/search/auth/login"
    method: "GET"
    return_content: true
    body_format: form-urlencoded
    body:
      - [ username, admin ]
      - [ password, Changeme123! ]
      - [ output_mode, json]
    status_code: 200
    validate_certs: no
  register: _result  

- name: Create Splunk indexes
  uri:
    url: "https://127.0.0.1:8089/services/data/indexes"
    method: "POST"
    return_content: true
    headers:
      Authorization: "Splunk {{ _result.json.sessionKey }}"
      Content-Type: application/json
    body_format: form-urlencoded
    body:
      - [ name, "{{ item.index_name }}"]
      - [ datatype, event ]
      - [ output_mode, json]
    status_code: [201,409]
    validate_certs: no
  with_items:
    - { index_name: 'osquery', sourcetype: "_json" }
    - { index_name: 'sysmon', sourcetype: "XmlWinEventLog:Microsoft-Windows-Sysmon/Operational" }
    - { index_name: 'zeek', sourcetype: "bro:json" }

- name: Create Splunk HEC inputs
  uri:
    url: "https://127.0.0.1:8089/servicesNS/admin/splunk_httpinput/data/inputs/http"
    method: "POST"
    return_content: true
    headers:
      Authorization: "Splunk {{ _result.json.sessionKey }}"
      Content-Type: application/json
    body_format: form-urlencoded
    body:
      - [ name, "{{ item.index_name }}_hec_token"]
      - [ index, "{{ item.index_name }}" ]
      - [ sourcetype, "{{ item.sourcetype }}" ]
      - [ output_mode, json]
    status_code: [201,409]
    validate_certs: no
  with_items:
    - { index_name: 'osquery', sourcetype: "_json" }
    - { index_name: 'sysmon', sourcetype: "XmlWinEventLog:Microsoft-Windows-Sysmon/Operational" }
    - { index_name: 'zeek', sourcetype: "bro:json" }

- name: Get Splunk get HEC inputs tokens
  uri:
    url: "https://127.0.0.1:8089/servicesNS/admin/splunk_httpinput/data/inputs/http/"
    method: "GET"
    return_content: true
    headers:
      Authorization: "Splunk {{ _result.json.sessionKey }}"
      Content-Type: application/json
    body_format: form-urlencoded
    body:
      - [ output_mode, json]
    status_code: [200]
    validate_certs: no
  register: _result  

- name: Setting host facts using complex arguments
  set_fact:
    "{{ item.content.index }}_hec_token": "{{ item.content.token }}"
  loop: "{{ _result.json.entry }}"
  no_log: true

##################################################################
# Modify Logstash output with HEC tokens
##################################################################
- name: Copy Splunk HEC outputs
  template:
    src: 'conf/ansible/splunk/31-output-splunk-hec.conf'
    dest: '/etc/logstash/conf.d/31-output-splunk-hec.conf'
    owner: 'logstash'
    group: 'logstash'
    mode: 0640

- name: Restart Logstash
  service:
    name: logstash
    enabled: yes
    state: restarted