ARG NGINX_VERSION
FROM nginx:${NGINX_VERSION}
ARG SERVICE_CONFIG

# Copy TLS cert and private key
COPY conf/tls/*.key /etc/ssl/private/nginx.key
COPY conf/tls/*.crt /etc/ssl/certs/nginx.crt

# Copy configs
COPY conf/docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY conf/docker/nginx/${SERVICE_CONFIG} /etc/nginx/conf.d/${SERVICE_CONFIG}