####################################################################
# Install/Setup Nginx
####################################################################
- name: Install/Setup Nginx
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - nginx

- name: Copy nginx.conf
  template:
    src: conf/ansible/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Copy Elastic configs
  template:
    src: 'conf/ansible/nginx/kibana.conf'
    dest: '/etc/nginx/conf.d/kibana.conf'
    owner: root
    group: root
    mode: 0644
  
- name: Copy Self-signed public cert for NGINX
  template:
    src: '{{ item }}'
    dest: '/etc/ssl/private/nginx.key'
    owner: 'root'
    group: 'root'
    mode: 0400
  with_fileglob:
    - conf/tls/*.key

- name: Copy Self-signed private key for NGINX
  template:
    src: '{{ item }}'
    dest: '/etc/ssl/certs/nginx.crt'
    owner: 'root'
    group: 'root'
    mode: 0644
  with_fileglob:
    - 'conf/tls/*.crt'

- name: Start Nginx service
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: NGINX healthcheck
  uri:
    url: "https://127.0.0.1:443/login?next=%2F"
    follow_redirects: none
    method: GET
    validate_certs: 'no'
    status_code: 200
  register: _result
  until: _result.status == 200
  retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5 # Every 5 seconds
