####################################################################
# Install/Setup Nginx
####################################################################
- name: Install/Setup Nginx
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - nginx

- name: Create TLS directory for NGINX
  file:
    path: /etc/nginx/tls
    owner: root
    group: root
    state: directory

- name: Copy nginx.conf
  template:
    src: conf/ansible/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Copy Splunk configs
  template:
    src: 'conf/ansible/nginx/splunk.conf'
    dest: '/etc/nginx/conf.d/splunk.conf'
    owner: root
    group: root
    mode: 0644
  
- name: Copy public cert for splunk
  template:
    src: 'conf/tls/docker.key'
    dest: '/etc/ssl/private/nginx.key'
    owner: 'root'
    group: 'root'
    mode: 0400

- name: Copy private key for splunk
  template:
    src: 'conf/tls/docker.crt'
    dest: '/etc/ssl/certs/nginx.crt'
    owner: 'root'
    group: 'root'
    mode: 0644

- name: Start Nginx service
  service:
    name: nginx
    state: restarted
    enabled: yes