####################################################################
# Generate Splunk HEC token
####################################################################
- name: Stat HEC token
  stat:
    path: '/tmp/splunk-zeek-hec-token.txt'
  register: splunk_zeek_hec_token_file

- name: Generate HEC token
  set_fact:
    SPLUNK_ZEEK_HEC_TOKEN: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=25') }}"
  when: not splunk_zeek_hec_token_file.stat.exists

- name: Write Splunk Zeek HEC token
  copy: 
    content: "{{ SPLUNK_ZEEK_HEC_TOKEN }}\n" 
    dest: /tmp/splunk-zeek-hec-token.txt
  when: not splunk_zeek_hec_token_file.stat.exists

- name: Read contents of Splunk Zeek HEC token file
  shell: "cat /tmp/splunk-zeek-hec-token.txt"
  register: file_token
  when: SPLUNK_ZEEK_HEC_TOKEN is undefined

- name: Generate HEC token
  set_fact:
    SPLUNK_ZEEK_HEC_TOKEN: "{{ file_token.stdout }}"
  when: SPLUNK_ZEEK_HEC_TOKEN is undefined

- name: Print contents of Splunk Zeek HEC token generation to console
  debug:
    msg: "{{ SPLUNK_ZEEK_HEC_TOKEN }}"
  when: SPLUNK_ZEEK_HEC_TOKEN is defined

####################################################################
# Setup Splunk HEC
####################################################################
- name: Create HEC local directory
  file:
    path: '/opt/splunk/etc/apps/splunk_httpinput/local'
    state: directory
    owner: 'splunk'
    group: 'splunk'

- name: Copy Splunk HEC system config
  template:
    src: 'conf/ansible/splunk/splunk-hec.conf'
    dest: '/opt/splunk/etc/apps/splunk_httpinput/local/inputs.conf'
    owner: 'splunk'
    group: 'splunk'
    mode: 0644

- name: Create Seach app local directory
  file:
    path: '/opt/splunk/etc/apps/search/local'
    state: directory
    owner: 'splunk'
    group: 'splunk'

- name: Copy Splunk Zeek HEC input
  template:
    src: 'conf/ansible/splunk/splunk-hec-zeek.conf'
    dest: '/opt/splunk/etc/apps/search/local/inputs.conf'
    owner: 'splunk'
    group: 'splunk'
    mode: 0644

- name: Restart Splunk service
  service:
    name: 'splunk'
    enabled: yes
    state: restarted

- name: Splunk HEC healthcheck
  uri:
    url: "http://127.0.0.1:8088/services/collector/health"
    follow_redirects: none
    method: GET
    remote_src: yes
    status_code: 200
  register: _result
  until: _result.status == 200
  retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5 # Every 5 seconds