name: Elastic Ansible playbook test

on: 
  # Only run when Elastic docker-compose changes
  push:
    paths:
      - 'group_vars/elastic.yml'
      - 'roles/elastic/*'
      - 'deploy_elastic.yml'

  # Only run when PR is requesting to merge with main
  pull_request:
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate TLS certs
        run: 'openssl req -x509 -new -nodes -keyout conf/tls/tls.key -out conf/tls/tls.crt -config conf/tls/tls.conf'
      
      - name: Comment out roles/init.yml
        run: |
          sed -i  "s?- import_tasks: 'roles/init.yml'?#- import_tasks: 'roles/init.yml'?g" deploy_elastic.yml

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: deploy_elastic.yml
          # Optional, directory where playbooks live
          directory: ./
          # Optional, literal inventory file contents
          inventory: |
            [elastic]
            127.0.01
          # Optional, SSH known hosts file content
          known_hosts: .known_hosts
          # Optional, additional flags to pass to ansible-playbook
          options: |
            --connection=local
            --limit elastic
            --verbose

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: pipeline_testers/requirements.txt

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      # the package installation will only be executed when the
      # requirements-files have changed.
      - run: pip3 install -r pipeline_testers/requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Wait until Elastic stack to start sucessfully
        run: |
          cat /tmp/elasticsearch-setup-passwords.txt
          until curl -s -u "elastic:$(cat /tmp/elasticsearch-setup-passwords.txt | grep elastic | awk -F' ' '{print $4}')" -X GET "http://127.0.0.1:9200/_cat/indices/*?v=true&s=index&pretty" | grep "uuid"
          do
            echo "[*] - Waiting on Elasticsearch to start"
            sleep 3
          done
          echo "[+] - Elasticsearch has started"

          until echo | openssl s_client -connect 127.0.0.1:5044 2> /dev/null | grep "BEGIN CERTIFICATE"
          do 
            echo "[*] - Waiting on logstash"
            sleep 3
          done
          echo "[+] - Logstash has started"

          
          tail -f /var/log/logstash/logstash-plain.log | grep -qx "Starting server on port: 5044"
          do 
            echo "[*] - Waiting on Logstash Beats input to start"
            sleep 3
          done
          echo "[+] - Logstash Beats input started"

      - name: Test
        run: |
          python3 pipeline_testers/beats_input_test.py \
          --platform elastic \
          --host 127.0.0.1 \
          --api_port 9200 \
          --ingest_port 5044 \
          --siem_username elastic \
          --siem_password $(cat .env | grep SIEM_PASSWORD | awk -F '=' '{print $2}')
