name: Splunk Ansible playbook test

on: 
  # Only run when Splunk docker-compose changes
  push:
    paths:
      - 'group_vars/splunk.yml'
      - 'roles/splunk/*'
      - 'deploy_splunk.yml'

  # Only run when PR is requesting to merge with main
  pull_request:
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate TLS certs
        run: 'openssl req -x509 -new -nodes -keyout conf/tls/tls.key -out conf/tls/tls.crt -config conf/tls/tls.conf'
      
      - name: Comment out roles/init.yml
        run: |
          sed -i  "s?- import_tasks: 'roles/init.yml'?#- import_tasks: 'roles/init.yml'?g" deploy_splunk.yml

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: deploy_splunk.yml
          # Optional, directory where playbooks live
          directory: ./
          # Optional, literal inventory file contents
          inventory: |
            [splunk]
            127.0.01
          # Optional, SSH known hosts file content
          known_hosts: .known_hosts
          # Optional, additional flags to pass to ansible-playbook
          options: |
            --connection=local
            --limit splunk
            --verbose

      - uses: actions/setup-python@v2
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: pipeline_testers/requirements.txt

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      # the package installation will only be executed when the
      # requirements-files have changed.
      - run: pip3 install -r pipeline_testers/requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Wait until Splunk starts sucessfully
        run: |
          until curl -k -s https://127.0.0.1:8089/servicesNS/admin/search/auth/login -d 'username=admin' -d "password=$(cat group_vars/all.yml| grep siem_password | awk -F ':' '{print $2}' | tr -d ' ' | tr -d \"'\")" -d 'output_mode=json' | grep "sessionKey"
          do
            echo "[*] - Waiting on Splunk to start"
            sleep 3
          done
          echo "[+] - Splunk has started"

      - name: Test
        run: |
          python3 pipeline_testers/beats_input_test.py \
          --platform splunk \
          --host 127.0.0.1 \
          --api_port 8089 \
          --ingest_port 5044 \
          --siem_username admin \
          --siem_password $(cat group_vars/all.yml| grep siem_password | awk -F ':' '{print $2}' | tr -d ' ' | tr -d "'")

